### PR TITLE
Revert "Prevent the automated workflow from running in fork"

### PR DESCRIPTION
**Pull request by kstich**
Reverts smithy-lang/smithy-language-server#135

### CODE REVIEW

**Comment by daddykotex** [comment]
it does not work?

**Comment by daddykotex** [comment]
absolutely sorry for a broken PR, do you know what's wrong?

**Comment by daddykotex** [comment]
The quotes maybe? https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
Their example is like this:

```yaml
name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats

```

**Comment by kstich** [comment]
Yeah, [from the literal docs](https://docs.github.com/en/actions/learn-github-actions/expressions#literals)

>However, if you do, you must use single quotes (') around the string.

**Pull request merged**
